const HEADER: &str = r#"// This file is automatically generated, do not edit directly.
// Contains headers for Ventrica, right now its mainly used on macOS. blah blah"#;

fn main() {
    let crate_dir = std::env::var("CARGO_MANIFEST_DIR").expect("Unable to get manifest directory");

    cbindgen::Builder::new()
        .with_crate(crate_dir)
        .with_language(cbindgen::Language::C)
        .with_include_guard("VENTRICA_H")
        .with_header(HEADER)
        .with_cpp_compat(true)
        .generate()
        .expect("Unable to generate bindings")
        .write_to_file("_build/include/ventrica.h");

    std::fs::copy("module/module.modulemap", "_build/include/module.modulemap")
        .expect("Unable to copy header");
}
